import {
  buildClientInstallCommand,
  buildOpenWrtInstallCommand,
  buildWindowsCMDInstallCommand,
  buildWindowsPowerShellInstallCommand,
  clientInstallCommandByKind,
  defaultClientInstallCommandForm,
  defaultFrontendSettingsForm,
  defaultTelegramBotForm,
  normalizeClientInstallCommandForm,
  normalizeFrontendSettingsForm,
  serializeFrontendSettingsForm,
  openWrtInstallScriptURL,
  powerShellQuote,
  shellQuote,
  type ClientInstallCommandForm,
  type ClientInstallCommandKind,
  type FrontendSettingsForm,
  type TelegramBotForm,
  windowsInstallScriptURL,
} from './adminFormHelpers'
import {
  APIError,
  buildAgentTerminalURL,
  buildDashboardRealtimeURL,
  fetchJSON,
  isUnauthorized,
  mergeRealtimeMetricsIntoAgents,
  mergeRealtimeSummary,
  sortAgentsByOrder,
} from './api'
import {
  actionKindLabel,
  actionStatusColor,
  actionStatusLabel,
  buildAddClientActionPayload,
  buildInboundActionPayload,
  buildInboundClientPayload,
  buildOutboundActionPayload,
  buildOutboundStreamSettings,
  buildRoutingActionPayload,
  buildUpsertRoutingActionPayload,
  buildVNextUser,
  buildXUIActionPayload,
  defaultAddClientActionForm,
  defaultInboundClientForm,
  defaultInboundActionForm,
  defaultOutboundActionForm,
  defaultRoutingActionForm,
  defaultTLSCertificateSelection,
  setRoutingList,
  splitTextList,
  type TLSCertificateSelectionForm,
  type XUIAddClientActionForm,
  type XUIInboundActionForm,
  type XUIInboundClientForm,
  type XUIOutboundActionForm,
  type XUIRoutingActionForm,
  XUI_ACTION_KINDS,
} from './xuiActionForms'

export const DASHBOARD_AUTO_REFRESH_MS = 20_000

export type { AgentViewMode, ConfigSectionKey } from './appHelperTypes'
export type {
  ClientInstallCommandForm,
  ClientInstallCommandKind,
  FrontendSettingsForm,
  TelegramBotForm,
} from './adminFormHelpers'
export type {
  TLSCertificateSelectionForm,
  XUIAddClientActionForm,
  XUIInboundActionForm,
  XUIInboundClientForm,
  XUIOutboundActionForm,
  XUIRoutingActionForm,
} from './xuiActionForms'

export { shortJSON, summarizeConfigAudit, confidenceLabel, formatDateInputFromMillis, dateInputToExpiryMillis, formatExpiryTime, formatDateTime, formatRelativeTime, scopeLabel, scopeColor, summarizeRule, statusColor, agentStatusLevel, summarizeAgent } from './appHelpersFormatting'
export { parseTagInput, formatTagInput, mergeTagOptions, mergeDashboardTagOptions, parseAddressInput, formatAddressInput, tagChipStyle } from './appHelpersTags'
export {
  normalizeRenewalConfig,
  normalizeClientBillings,
  clientBillingKey,
  billingKeyForClient,
  defaultClientBilling,
  normalizeClientTrafficMultiplier,
  scaleClientTraffic,
  findClientBilling,
  upsertClientBilling,
  dateInputToStartMillis,
  clientBillingPatchFromStart,
  effectiveClientBillingStartTime,
  effectiveClientBillingExpiryTime,
  calculateRenewalStatus,
  formatRenewalHint,
  calculateRenewalPeriod,
  parseLocalDate,
  startOfLocalDay,
  addRenewalCycle,
  subtractRenewalCycle,
  addClampedMonths,
  daysBetween,
  formatLocalDate,
} from './appHelpersBilling'
export {
  normalizeEntryConfig,
  normalizeImportDomain,
  normalizeEntryProtocol,
  buildSectionSavePayload,
  mergeSavedSectionIntoDraft,
  configSectionLabel,
  configSignature,
  createEmptyManagedConfig,
  normalizeManagedConfig,
  normalizeXUIOverview,
} from './appHelpersConfig'
export {
  hasSelectedTag,
  isAgentRunning,
  topologyMatchesSelectedTag,
  findOutboundLinkedClient,
  chainMatchesSelectedTag,
  readStoredAgentViewMode,
  storeAgentViewMode,
  agentViewModeStorageKey,
  isClientOnline,
  xrayIssueLabel,
  agentDisplayStatus,
  countryFlag,
  agentCountryCode,
  explicitAgentCountryCode,
  explicitCountryCodeFromText,
  normalizeCountryCode,
  formatAgentLocation,
  formatGeoLabel,
  countryName,
  outboundElementId,
  ruleElementId,
  nodeElementId,
  normalizeNodeAnchorLabel,
  sanitizeFragment,
} from './appHelpersAgent'
export {
  APIError,
  fetchJSON,
  buildDashboardRealtimeURL,
  buildAgentTerminalURL,
  mergeRealtimeMetricsIntoAgents,
  sortAgentsByOrder,
  mergeRealtimeSummary,
  isUnauthorized,
  XUI_ACTION_KINDS,
  defaultTLSCertificateSelection,
  defaultInboundClientForm,
  defaultInboundActionForm,
  defaultOutboundActionForm,
  defaultRoutingActionForm,
  defaultAddClientActionForm,
  defaultTelegramBotForm,
  defaultClientInstallCommandForm,
  normalizeClientInstallCommandForm,
  defaultFrontendSettingsForm,
  normalizeFrontendSettingsForm,
  serializeFrontendSettingsForm,
  clientInstallCommandByKind,
  buildClientInstallCommand,
  buildOpenWrtInstallCommand,
  buildWindowsPowerShellInstallCommand,
  buildWindowsCMDInstallCommand,
  windowsInstallScriptURL,
  openWrtInstallScriptURL,
  shellQuote,
  powerShellQuote,
  buildXUIActionPayload,
  buildAddClientActionPayload,
  buildInboundActionPayload,
  buildInboundClientPayload,
  buildOutboundActionPayload,
  buildUpsertRoutingActionPayload,
  buildVNextUser,
  buildOutboundStreamSettings,
  buildRoutingActionPayload,
  setRoutingList,
  splitTextList,
  actionKindLabel,
  actionStatusLabel,
  actionStatusColor,
}
